export const themeTokens = {
  color: {
    backgroundCanvas: "#fbf9f8",
    backgroundCanvasSoft: "#f5f3f3",
    surfacePrimary: "#ffffff",
    surfaceSecondary: "#f4f7fb",
    surfaceMuted: "#eaf0f8",
    surfaceGlass: "rgba(255, 255, 255, 0.72)",
    textPrimary: "#1b1c1c",
    textSecondary: "#4d5766",
    textMuted: "rgba(27, 28, 28, 0.56)",
    textOnAccent: "#ffffff",
    accentPrimary: "#0057c2",
    accentStrong: "#006ef2",
    accentSoft: "rgba(0, 87, 194, 0.12)",
    borderSubtle: "rgba(114, 119, 134, 0.14)",
    borderAccent: "rgba(0, 87, 194, 0.22)",
    overlayStrong: "rgba(13, 23, 41, 0.68)",
    overlaySoft: "rgba(13, 23, 41, 0.18)",
    success: "#2f7d5b",
  },
  gradient: {
    page:
      "radial-gradient(circle at top left, rgba(0, 110, 242, 0.16), transparent 30%), radial-gradient(circle at top right, rgba(0, 87, 194, 0.11), transparent 26%), linear-gradient(180deg, #fbf9f8 0%, #f4f7fb 58%, #fbf9f8 100%)",
    hero:
      "radial-gradient(circle at top left, rgba(0, 110, 242, 0.15), transparent 36%), linear-gradient(180deg, rgba(255,255,255,0.62), rgba(255,255,255,0.94))",
    accent: "linear-gradient(135deg, #0057c2 0%, #006ef2 100%)",
    accentSoft: "linear-gradient(135deg, rgba(0, 87, 194, 0.1), rgba(0, 110, 242, 0.18))",
    accentMuted: "linear-gradient(135deg, rgba(0, 87, 194, 0.08), rgba(0, 110, 242, 0.14))",
    card: "linear-gradient(180deg, rgba(255,255,255,0.96), rgba(244,247,251,0.94))",
    glass: "linear-gradient(180deg, rgba(255,255,255,0.82), rgba(255,255,255,0.62))",
    map: "radial-gradient(circle at center, rgba(0, 110, 242, 0.12), transparent 32%), linear-gradient(180deg, #fbf9f8 0%, #eef3fb 100%)",
    heroFade: "linear-gradient(90deg, rgba(251,249,248,0.98) 0%, rgba(251,249,248,0.92) 52%, rgba(251,249,248,0.45) 100%)",
  },
  radius: {
    pill: "999px",
    hero: "40px",
    panel: "32px",
    card: "28px",
    tile: "24px",
    media: "24px",
    control: "18px",
    compact: "14px",
  },
  shadow: {
    floating: "0 24px 48px -12px rgba(27, 28, 28, 0.08)",
    panel: "0 18px 40px -14px rgba(27, 28, 28, 0.09)",
    accent: "0 20px 40px rgba(0, 87, 194, 0.18)",
    subtle: "0 12px 30px rgba(27, 28, 28, 0.08)",
  },
  spacing: {
    pageX: "clamp(24px, 4vw, 56px)",
    pageTop: "118px",
    sectionGap: "112px",
    panelPadding: "32px",
    cardPadding: "24px",
    compactGap: "12px",
  },
  typography: {
    body: '"Manrope", "Noto Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif',
    display: '"Manrope", "Noto Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif',
    hero: "clamp(3.8rem, 9vw, 6.2rem)",
    section: "clamp(2.6rem, 6vw, 4.4rem)",
    cardTitle: "clamp(1.7rem, 3vw, 2.15rem)",
    bodyLineHeight: "1.8",
  },
  motion: {
    fast: "180ms",
    normal: "320ms",
    slow: "520ms",
    hoverLift: "-4px",
  },
};

export const themeVars = {
  "--color-background-canvas": themeTokens.color.backgroundCanvas,
  "--color-background-canvas-soft": themeTokens.color.backgroundCanvasSoft,
  "--color-surface-primary": themeTokens.color.surfacePrimary,
  "--color-surface-secondary": themeTokens.color.surfaceSecondary,
  "--color-surface-muted": themeTokens.color.surfaceMuted,
  "--color-surface-glass": themeTokens.color.surfaceGlass,
  "--color-text-primary": themeTokens.color.textPrimary,
  "--color-text-secondary": themeTokens.color.textSecondary,
  "--color-text-muted": themeTokens.color.textMuted,
  "--color-text-on-accent": themeTokens.color.textOnAccent,
  "--color-accent-primary": themeTokens.color.accentPrimary,
  "--color-accent-strong": themeTokens.color.accentStrong,
  "--color-accent-soft": themeTokens.color.accentSoft,
  "--color-border-subtle": themeTokens.color.borderSubtle,
  "--color-border-accent": themeTokens.color.borderAccent,
  "--color-overlay-strong": themeTokens.color.overlayStrong,
  "--color-overlay-soft": themeTokens.color.overlaySoft,
  "--gradient-page": themeTokens.gradient.page,
  "--gradient-hero": themeTokens.gradient.hero,
  "--gradient-accent": themeTokens.gradient.accent,
  "--gradient-accent-soft": themeTokens.gradient.accentSoft,
  "--gradient-accent-muted": themeTokens.gradient.accentMuted,
  "--gradient-card": themeTokens.gradient.card,
  "--gradient-glass": themeTokens.gradient.glass,
  "--gradient-map": themeTokens.gradient.map,
  "--gradient-hero-fade": themeTokens.gradient.heroFade,
  "--radius-pill": themeTokens.radius.pill,
  "--radius-hero": themeTokens.radius.hero,
  "--radius-panel": themeTokens.radius.panel,
  "--radius-card": themeTokens.radius.card,
  "--radius-tile": themeTokens.radius.tile,
  "--radius-media": themeTokens.radius.media,
  "--radius-control": themeTokens.radius.control,
  "--radius-compact": themeTokens.radius.compact,
  "--shadow-floating": themeTokens.shadow.floating,
  "--shadow-panel": themeTokens.shadow.panel,
  "--shadow-accent": themeTokens.shadow.accent,
  "--shadow-subtle": themeTokens.shadow.subtle,
  "--space-page-x": themeTokens.spacing.pageX,
  "--space-page-top": themeTokens.spacing.pageTop,
  "--space-section-gap": themeTokens.spacing.sectionGap,
  "--space-panel-padding": themeTokens.spacing.panelPadding,
  "--space-card-padding": themeTokens.spacing.cardPadding,
  "--space-compact-gap": themeTokens.spacing.compactGap,
  "--font-body": themeTokens.typography.body,
  "--font-display": themeTokens.typography.display,
  "--font-size-hero": themeTokens.typography.hero,
  "--font-size-section": themeTokens.typography.section,
  "--font-size-card-title": themeTokens.typography.cardTitle,
  "--line-height-body": themeTokens.typography.bodyLineHeight,
  "--motion-fast": themeTokens.motion.fast,
  "--motion-normal": themeTokens.motion.normal,
  "--motion-slow": themeTokens.motion.slow,
  "--motion-hover-lift": themeTokens.motion.hoverLift,
};
