export const themeTokens = {
  color: {
    backgroundCanvas: "#111111",
    backgroundCanvasSoft: "#171717",
    surfacePrimary: "#1C1B19",
    surfaceSecondary: "#262420",
    surfaceMuted: "#2F2B25",
    textPrimary: "#F3EFE7",
    textSecondary: "#CDC6BA",
    textMuted: "rgba(243, 239, 231, 0.56)",
    textOnAccent: "#1C1B19",
    accentPrimary: "#D9C18C",
    accentStrong: "#A96B31",
    accentSoft: "rgba(217, 193, 140, 0.18)",
    borderSubtle: "rgba(255, 255, 255, 0.08)",
    borderAccent: "rgba(217, 193, 140, 0.26)",
    overlayStrong: "rgba(0, 0, 0, 0.72)",
    overlaySoft: "rgba(0, 0, 0, 0.42)",
    success: "#8EC58E",
  },
  gradient: {
    page:
      "radial-gradient(circle at top left, rgba(217, 193, 140, 0.18), transparent 28%), radial-gradient(circle at top right, rgba(169, 107, 49, 0.16), transparent 24%), linear-gradient(180deg, #111111 0%, #171717 100%)",
    hero:
      "radial-gradient(circle at top, rgba(217, 193, 140, 0.24), transparent 42%), linear-gradient(180deg, rgba(17,17,17,0.28), rgba(17,17,17,1))",
    accent: "linear-gradient(135deg, #D9C18C 0%, #A96B31 100%)",
    accentSoft: "linear-gradient(135deg, rgba(217,193,140,0.2), rgba(169,107,49,0.36))",
    accentMuted: "linear-gradient(135deg, rgba(217,193,140,0.18), rgba(169,107,49,0.26))",
    card: "linear-gradient(180deg, rgba(255,255,255,0.04), rgba(255,255,255,0.01))",
    map: "radial-gradient(circle at center, rgba(169,107,49,0.18), transparent 32%), linear-gradient(180deg, #131313 0%, #111111 100%)",
    heroFade: "linear-gradient(90deg, rgba(17,17,17,1) 0%, rgba(17,17,17,0.88) 58%, rgba(17,17,17,0) 100%)",
  },
  radius: {
    pill: "999px",
    hero: "34px",
    panel: "30px",
    card: "26px",
    tile: "22px",
    media: "20px",
    control: "18px",
    compact: "14px",
  },
  shadow: {
    floating: "0 24px 60px rgba(0, 0, 0, 0.38)",
    panel: "0 20px 48px rgba(0, 0, 0, 0.32)",
    accent: "0 18px 40px rgba(0, 0, 0, 0.34)",
    subtle: "0 12px 30px rgba(0, 0, 0, 0.22)",
  },
  spacing: {
    pageX: "clamp(24px, 4vw, 56px)",
    pageTop: "96px",
    sectionGap: "96px",
    panelPadding: "28px",
    cardPadding: "24px",
    compactGap: "12px",
  },
  typography: {
    body: '"Noto Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif',
    display: '"Noto Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif',
    hero: "clamp(3.2rem, 9vw, 5.6rem)",
    section: "clamp(2.4rem, 6vw, 4.2rem)",
    cardTitle: "clamp(1.6rem, 3vw, 2rem)",
    bodyLineHeight: "1.8",
  },
  motion: {
    fast: "180ms",
    normal: "320ms",
    slow: "520ms",
    hoverLift: "-4px",
  },
};

export const themeVars = {
  "--color-background-canvas": themeTokens.color.backgroundCanvas,
  "--color-background-canvas-soft": themeTokens.color.backgroundCanvasSoft,
  "--color-surface-primary": themeTokens.color.surfacePrimary,
  "--color-surface-secondary": themeTokens.color.surfaceSecondary,
  "--color-surface-muted": themeTokens.color.surfaceMuted,
  "--color-text-primary": themeTokens.color.textPrimary,
  "--color-text-secondary": themeTokens.color.textSecondary,
  "--color-text-muted": themeTokens.color.textMuted,
  "--color-text-on-accent": themeTokens.color.textOnAccent,
  "--color-accent-primary": themeTokens.color.accentPrimary,
  "--color-accent-strong": themeTokens.color.accentStrong,
  "--color-accent-soft": themeTokens.color.accentSoft,
  "--color-border-subtle": themeTokens.color.borderSubtle,
  "--color-border-accent": themeTokens.color.borderAccent,
  "--color-overlay-strong": themeTokens.color.overlayStrong,
  "--color-overlay-soft": themeTokens.color.overlaySoft,
  "--gradient-page": themeTokens.gradient.page,
  "--gradient-hero": themeTokens.gradient.hero,
  "--gradient-accent": themeTokens.gradient.accent,
  "--gradient-accent-soft": themeTokens.gradient.accentSoft,
  "--gradient-accent-muted": themeTokens.gradient.accentMuted,
  "--gradient-card": themeTokens.gradient.card,
  "--gradient-map": themeTokens.gradient.map,
  "--gradient-hero-fade": themeTokens.gradient.heroFade,
  "--radius-pill": themeTokens.radius.pill,
  "--radius-hero": themeTokens.radius.hero,
  "--radius-panel": themeTokens.radius.panel,
  "--radius-card": themeTokens.radius.card,
  "--radius-tile": themeTokens.radius.tile,
  "--radius-media": themeTokens.radius.media,
  "--radius-control": themeTokens.radius.control,
  "--radius-compact": themeTokens.radius.compact,
  "--shadow-floating": themeTokens.shadow.floating,
  "--shadow-panel": themeTokens.shadow.panel,
  "--shadow-accent": themeTokens.shadow.accent,
  "--shadow-subtle": themeTokens.shadow.subtle,
  "--space-page-x": themeTokens.spacing.pageX,
  "--space-page-top": themeTokens.spacing.pageTop,
  "--space-section-gap": themeTokens.spacing.sectionGap,
  "--space-panel-padding": themeTokens.spacing.panelPadding,
  "--space-card-padding": themeTokens.spacing.cardPadding,
  "--space-compact-gap": themeTokens.spacing.compactGap,
  "--font-body": themeTokens.typography.body,
  "--font-display": themeTokens.typography.display,
  "--font-size-hero": themeTokens.typography.hero,
  "--font-size-section": themeTokens.typography.section,
  "--font-size-card-title": themeTokens.typography.cardTitle,
  "--line-height-body": themeTokens.typography.bodyLineHeight,
  "--motion-fast": themeTokens.motion.fast,
  "--motion-normal": themeTokens.motion.normal,
  "--motion-slow": themeTokens.motion.slow,
  "--motion-hover-lift": themeTokens.motion.hoverLift,
};
